### ISSUE TITLE
Problem when running python3 main.py in docker

### ISSUE THREAD

**Issue by kynehc** [NobleMathews/FuzzSliceICSE#1]
Hi, 

I am trying FuzzSlice: build up the docker from scratch and running the main.py. But somehow I get this error:
```
root@a0671c400b87:/StaticSlicer# python3 main.py
2023-10-12 12:38:42.915 | INFO     | __main__:create_build_log:820 - Started build
Configuring OpenSSL version 3.2.0-alpha3-dev for target linux-x86_64
Using os-specific seed configuration
Created configdata.pm
Running configdata.pm
Created Makefile.in
Created Makefile
Created include/openssl/configuration.h

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL.md file first)      ***
***                                                                ***
**********************************************************************
2023-10-12 12:54:48.257 | INFO     | __main__:create_build_log:860 - Build Log created
2023-10-12 12:54:48.295 | INFO     | __main__:fix_build_log:883 - Build Log fixed
2023-10-12 12:54:48.296 | INFO     | __main__:run_rats:712 - Running Rats
Traceback (most recent call last):
  File "main.py", line 1198, in <module>
    prep_preprocessed_output(temp_loc)
  File "main.py", line 1154, in prep_preprocessed_output
    if result.group(1):
AttributeError: 'NoneType' object has no attribute 'group'
root@a0671c400b87:/StaticSlicer#
```

would you check why this happen? Thanks!

**Comment by NobleMathews** [comment]
Hi! Thanks for checking out our project out and highlighting this bug. There was an issue with the submodule hashes not being committed correctly when we made this copy of the project. 

I have tested setting up a fresh clone following the steps outlined in the Readme and am not running into any issues.

P.s. the targets.txt file for each repo is currently updated manually. I have pushed the set we use in the paper which is just filtered from the static analysis scans but you would need to change this and the configuration file based on your requirements

Could you try rebuilding from scratch and see if you run into the issue again?

**Comment by NobleMathews** [comment]
I am assuming this was resolved, please reopen an issue if you run into any other issues!
